name: Run Ole Miss Price Scraper

on:
  workflow_dispatch:
  
  schedule:
    - cron: '*/11 * * * *'  # Schedule the workflow to run every 5 minutes

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 122

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install pipenv        
      run: pip install pipenv 

    - name: Install dependencies using pipenv        
      run: pipenv install --deploy --system 

    - name: Run script
      id: run-script
      run: |
        python scrape-ole-miss.py

      env:
        API_KEY: ${{ secrets.PO_API_KEY }}
        USER_KEY: ${{ secrets.PO_USER_KEY }}

    - name: Print File Contents
      run: |
        cat output_results.csv
    - name: Print condition_value
      run: |
        echo "condition_value: ${{ steps.run-script.outputs.condition_value }}"

    # - name: Push Build Status Notifications
    #   if: ${{ steps.run-script.outputs.condition_value == 'true' }}
    #   uses: desiderati/github-action-pushover@v1
    #   with:
    #     job-status: ${{ job.status }}
    #     pushover-api-token: ${{ secrets.PO_API_KEY }}
    #     pushover-user-key: ${{ secrets.PO_USER_KEY }}
    - name: Push Build Status Notifications
      if: ${{ steps.run-script.outputs.condition_value == 'true' }}
      uses: zerok/pushover-action@master
      with:
        user: ${{ secrets.PO_USER_KEY }}
        token: ${{ secrets.PO_API_KEY }}
        title: Ole Miss Football availiability
        message: ${{ steps.run-script.outputs.result_string }}
        url: ${{ steps.run-script.outputs.url }}