name: Run Price Scraper

on:
  workflow_dispatch:
  
  # schedule:
  #   - cron: '0 0 * * *'  # Schedule the workflow to run daily at midnight

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4
        pip install pandas
        pip install --upgrade pip setuptools==57.5.0
        pip install --upgrade python-pushover

    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 114

    - name: Run script
      run: python scrape-hilton.py
      env:
        API_KEY: ${{ secrets.PO_API_KEY }}
        USER_KEY: ${{ secrets.PO_USER_KEY }}

    - name: Print File Contents
      run: |
        cat output_results.csv
