name: Run Alaska Scraper

on:
  workflow_dispatch:
  
  # schedule:
  #   - cron: '*/11 * * * *'  # Schedule the workflow to run every 10 minutes

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 122

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install pipenv        
      run: pip install pipenv 

    - name: Install dependencies using pipenv        
      run: pipenv install --deploy --system 

    - name: Run script
      id: run-script
      run: |
        python scrape-alaskaair.py

  - name: Commit and push changes
    run: |
      git config --global user.name 'github-actions[bot]'
      git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      git add scrape_results.csv
      git commit -m "Update scrape results"
      git push
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}